import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import { CopyToClipboard } from "react-copy-to-clipboard";

const Home: NextPage = () => {
  const [copyValue, setCopyValue] = useState<string>("test");

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <input
          value={copyValue}
          onChange={({ target: { value } }) => setCopyValue(value)}
        />

        <CopyToClipboard text={copyValue} onCopy={() => {}}>
          <button>Copy to clipboard with button</button>
        </CopyToClipboard>
      </main>
    </div>
  );
};

export default Home;
